### ISSUE TITLE
Ignore editable pypi dependencies

### ISSUE THREAD

**Issue by noamgot** [Quantco/pixi-pack#127]
With the completion of supporting pypi packages, it would be nice if pixi-pack could ignore editable pypi dependencies.
It is a very common case where one adds the package they develop as an editable dependency (and, in fact, it happens by default when initializing a pixi project with `--format pyproject`):

```toml
[tool.pixi.pypi-dependencies]
my_pkg = {path = ".", editable = true}
```

I think it would make sense to ignore these dependencies by default.
