### ISSUE TITLE
Allow python wheels from local path to be packed

### ISSUE THREAD

**Issue by MartinHenselHLL** [Quantco/pixi-pack#179]
Please allow python wheels from local paths to be packed into an environment.

### Current situation

Pypi packages can be specified in the pixi.toml as references to be looked up on the package index or as direct paths to the package (from https://github.com/prefix-dev/pixi/blob/main/examples/pypi-source-deps/pixi.toml):
```toml
[pypi-dependencies]
# You can also directly add a source dependency from file
minimal-project = { path = "./minimal-project", editable = true }
```
The same is possible for wheels:
```toml
[pypi-dependencies]
minimal-project = { path = "./dist/minimal-project-0.0.1-py3-none-any.whl" }
```

This can in theory be used to first build a package with the pixi build system integration and then pack the just-built package into an environment using `pixi-pack`. However at the moment pypi references that lead to a local path are rejected by the packer in the `download_pypi_package` function:
https://github.com/Quantco/pixi-pack/blob/093054e536b1eec816d5e9663e87ce571acaf201/src/pack.rs#L800-L803

### Attempted resolutions without changes to the codebase

This rejection can at the moment **not** be circumvented by any of the following tricks:
- Specifying the package location as a file-url:
  ```toml
  [pypi-dependencies]
  minimal-project = { url = "file:///path/to/project/dist/minimal-project-0.0.1-py3-none-any.whl" }
  ```
  This dereferences as a path (probably in `uv`) and is then blocked by the check in `download_pypi_package`.
- Specifying the package as just a version number and providing a `find-links` argument in the `pypi-options` table to look for packages in the local folder (in addition to the pypi registry):
  ```toml
  [project.pypi-options]
  index-url = "https://pypi.org/simple"
  find-links = [ { path = "./dist" } ]
  
  [pypi-dependencies]
  minimal-project = "==0.0.1"
  ```
  This allows pypi to find the project wheel file in the local `./dist` folder but it also dereferences to a path (again probably in `uv`) and is rejected by the packer in the same line of `download_pypi_package`.
- Using the `pixi-pack` cache to circumvent the need to download and dereference the package. By using the command-line argument `--use-cache ./cache` I created the local cache that includes all conda and pypi packages needed for the environment, except the local package. I then copied the local package wheel into the pypi cache folder `./cache/pypi` and tried packing again. Even though the package is in the local cache, the package definition is rejected because the dereferences-to-path check occurs before the cache is checked. As `uv` still needs to be able resolve the package definition and it resolves to a local path (it is not available on pypi), the package is still rejected.

### Possible workaround

For the time being the only solution I found is to host a local pypi simple API server (e.g. `pypiserver`) for the locally built package and to add the local server as `extra-index-urls` to the pypi-options.

Example:
- In a terminal:
  ```bash
  pip install pypiserver
  pypi-server run -p 8080 ./dist
  ```
- In `pixi.toml`:
  ```toml
  [project.pypi-options]
  index-url = "https://pypi.org/simple"
  extra-index-urls = [ "http://localhost:8080" ]
  ```

This is dereferenced by `uv` as a url and therefore the check in `download_pypi_package` allows the package to be added to the packed environment.

### Suggested solution

The function `download_pypi_package` already includes code to reuse local packages from the local cache. Instead of outright rejecting local paths, the same mechanism could be used to copy local packages from the given path to the temporary output path:
https://github.com/Quantco/pixi-pack/blob/093054e536b1eec816d5e9663e87ce571acaf201/src/pack.rs#L810-L817

As I am not a Rust developer I can unfortunately not provide an implementation of the request, but the necessary changes should be minimal and localized to the function `download_pypi_package`. Handling of non-existent paths is included in the cache-lookup code and handling of non-wheel packages is included in the later packing stage, so no additional error case checking should be required.

### Use-case

I try to implement a versioning into my created environment. `pixi-pack`, unlike `conda-constructor`, does not allow the inclusion of post-install scripts or the likes. Therefore to track the version of the environment I build a small versioning package with the sole purpose to report a version number of the environment (either via package version in pip or via command that prints the same version number). This package is volatile and changes whenever a new version of the environment is built (to include the fixed version number of the environment). Therefore the package is built as part of the CI/CD pipeline that creates the packed environment and there is little sense in publishing the versioning package outside of the packed environment.

Having the option to include this locally built wheel package in the environment by specifying the path to the local wheel means that I do not have to run a temporary local pypi server inside the CI/CD container to serve a single tiny package for the `pixi-pack` tool.

In addition, supporting the local path specification would unify the interface for `pixi` and `pixi-pack`, as `pixi` already allows and supports building environments that include local wheels (and source packages, but that is already handled and documented by `pixi-pack` as unsupported).
