### ISSUE TITLE
"could not read package timestamp" when packing an environment for osx-64

### ISSUE THREAD

**Issue by gerlero** [Quantco/pixi-pack#60]
Thanks for developing this package. I'm having this issue that I haven't been able to debug. 

Steps to reproduce it are:

```bash
curl -O https://raw.githubusercontent.com/gerlero/openfoam-app/refs/heads/main/pixi.toml
pixi run pixi-pack pack --environment openfoam --platform osx-64 #Not an issue if --platform osx-arm64
```

Which invariably causes this error:

```
⏳ Downloading 31 packages...
Error: could not download package: could not read package timestamp
```

This problem first started with pixi-pack 0.2.0 (it didn't fail with 0.1.8).

**Comment by pavelzw** [comment]
We made the packs reproducible in 0.2.0 by setting the correct timestamp. I'll take a look into your issue, it seems to me that one of your packages have a bad timestamp set in the metadata.

**Comment by pavelzw** [comment]
The `mpi-1.0-openmpi.tar.bz2` package on conda-forge doesn't have a timestamp field in `pixi.lock`.

![image](https://github.com/user-attachments/assets/310f12b4-f643-4796-9dba-d81783bab488)

**Comment by pavelzw** [comment]
This is a more minimal reproducer

```toml
[project]
channels = ["conda-forge"]
name = "no-timestamp"
platforms = ["osx-64"]

[dependencies]
mpi = { version = "1.0", build = "openmpi" }
```

```yml
version: 5
environments:
  default:
    channels:
    - url: https://conda.anaconda.org/conda-forge/
    packages:
      osx-64:
      - conda: https://conda.anaconda.org/conda-forge/osx-64/mpi-1.0-openmpi.tar.bz2
packages:
- kind: conda
  name: mpi
  version: '1.0'
  build: openmpi
  subdir: osx-64
  url: https://conda.anaconda.org/conda-forge/osx-64/mpi-1.0-openmpi.tar.bz2
  sha256: 1326b28195e8808cebc18a593f84c5cbd606826a150dd7e0365f11b86238b5df
  md5: 8c3bc725bf4d10fc6e56031f7543771f
  arch: x86_64
  platform: osx
  license: BSD 3-clause
  size: 4394
```

```
pixi-pack pack --platform osx-64
```
