### ISSUE TITLE
pixi-pack 0.3.2 does not support pyproject.toml in certain scenarios

### ISSUE THREAD

**Issue by dennis-wey** [Quantco/pixi-pack#98]
For me pixi-pack stopped working with version 0.3.2. 
I'm using a pyproject.toml as manifest, here is a reduced example:

```toml
[project]
name = "pixi-test"
requires-python = ">= 3.12"
dynamic = ['version']

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.feature.prod.dependencies]
pydantic = "*"

[tool.pixi.feature.prod.pypi-dependencies]
pixi_test = { path = ".", editable = true }

[tool.pixi.feature.actions.dependencies]
pixi-pack = "*"

[tool.pixi.environments]
prod = ["prod"]
actions = ["actions"]
```
calling 
```bash
pixi run --environment actions pixi-pack pack --environment prod --platform linux-64 --ignore-pypi-errors
```
results in 
```
/Users/denniswayland/ghq/github.com/BY-Product-Development/plan-lde-ui-backend/pixi-test/pixi.toml
```

This only occured when using pixi-pack version 0.3.2. It's working with 0.3.1
